### ISSUE TITLE
Notes from first transcription workshop

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/DaSSCo-Transcription#1]
- [x] Type up notes from workshop held on 07/11/2023 at NHMD, including attendee
- [x] Send notes for review to Chelsea, Pip, Astrid, Bhupjit
- [x] Finalise notes for sending out
- [x] Collect presentations from workshop
- [x] Send notes out

**Due date: 11/01/2024**

**Comment by PipBrewer** [comment]
Notes edited and will send around in email for checking by 11/01/2024

[Notes from Transcription Workshop held on 20231107_PBedits.docx](https://github.com/NHMDenmark/DaSSCo-Transcription/files/13792922/Notes.from.Transcription.Workshop.held.on.20231107_PBedits.docx)

**Comment by AstridBVW** [comment]
Notes are finalised and ready to be send out.

[Notes from Transcription Workshop held on 20231107_Final.docx](https://github.com/NHMDenmark/DaSSCo-Transcription/files/13888400/Notes.from.Transcription.Workshop.held.on.20231107_Final.docx)

**Comment by AstridBVW** [comment]
The notes were sent out 20240116.

They have been saved in the following location: 
N:\SCI-SNM-DigitalCollections\DaSSCo\Transcription\Workshop 1 November 2023\Reporting
