### ISSUE TITLE
Finalise V1 interface and test

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/DaSSCo-Transcription#11]
The aim of this ticket is to test the initial V1 interface and identify any serious issues and bugs, become familar with it, and to start a list of future potential development

Parts of task:

- [x] Become user (admin level) and get access and training from Joaquim
- [x] Create dummy data sets to test transcription platform
- [x] Play around with platform, including creating projects to thoroughly test
- [x] Make a list of bugs and recommendations to be discussed and prioritised
- [x] Add Danish text to platform (e.g., field names, help etc).

This task must be complete by end of September 2024

**Comment by AstridBVW** [comment]
While I am waiting to get access to the transcription platform for testing, I am preparing what I can. 

I have prepared dummy datasets of varying size based on NHMD Entomology collection object records that has attachments of the JPEG format. For creating a transcription project, you need a dataset with NHMD numbers and image URLs for the associated attachments. I have made dummy datasets that match this criteria.

**Comment by AstridBVW** [comment]
There are some problems with the server provided for the transcription platform so we are temporarily using a cloud solution instead. This is for testing purposes only while the problems are sorted out.

Joaquim has sent me the link to the test platform, I have been able to create an account, and Joaquim has granted me admin access.
He is still fixing some stuff so I will give him a few more days to work on it before I start testing. I will continue with preparing the data in the meantime.

**Comment by AstridBVW** [comment]
@PipBrewer @joaquimsantos1978 I am in the process of testing the transcription platform. I will continue this on Monday 20241021, and if there is time I can provide you with some feedback at our catch up meeting on Tuesday. I will of course also provide it here.

**Comment by AstridBVW** [comment]
I gave an update and feedback on the testing today at our transcription catch up meeting (20241022). We ended up with a list of action points, these will be created as tickets and will be prioritised. Some of these action points will be prioritised for version 1 and some for version 2.

For version 1 specifically, some things are missing from the platform and will be fixed by Joaquim (see #10 ).

**Comment by AstridBVW** [comment]
Changes are still being made to the platform based on my feedback so testing is on-going. 

English and Danish text have been added to the platform for the locality and date fields (field captions, helpers etc.). The About and Tutorial pages still need content but this is not a priority at the moment and will be done at a later point. A separate ticket will be created for this.

**Comment by AstridBVW** [comment]
Platform is almost ready, minor testing and re-testing is required. If anything major comes up, a new ticket will be created.
