### ISSUE TITLE
Dung beetles, missing images and more

### ISSUE THREAD

**Issue by AstridBVW** [NHMDenmark/DaSSCo-Transcription#21]
In preparation for transcription of the dung beetle images, I am compiling a list of all the image folders on the N-drive containing dung beetle images.

During this process I discovered that some of the Specify records did not have a corresponding image. I also found one blurry image and an image of a specimen that was not assigned a barcode (no barcode in the image and no Specify record). This needs to be fixed for the transcription of these specimens to move forward.

Below is a list of what needs to happen:

1) The following specimens need to be located in the collection and imaged (only imaged, they already have a barcode and a corresponding Specify record) (catalog number, taxon, cataloged date):

- 1707652, Aphodius coenosus, 2024-03-15
- 1707654, Aphodius coenosus, 2024-03-15
- 1707655, Aphodius coenosus, 2024-03-15
- 1708036, Aphodius equestris, 2024-03-20
- 1743112, Aphodius borealis, 2024-05-30

2) The following specimen has a blurry image, the image need to be re-taken:

- 1744017, Aphodius fimetarius, 2024-06-20

3) The following specimen needs to be entirely re-digitised since it was not assigned a barcode and not entered into the DigiApp:

Taxon: Aphodius scybalarius
Specimen can be found between NHMD1710275 and NHMD1710276

I will let the digitiser team decide whether or not it is necessary to entirely replicate the set-up used when all the dung beetles were imaged (PIOF0002, dung beetle stage and POV).

When it is done, please provide me with the information on where I can find the images on the N-drive.

**Comment by JesperMJensen** [comment]
The following specimens have been re-imaged on 2024-11-21, retaining the NHMD number previously assigned.
1707652, Aphodius coenosus, 2024-03-15
1707654, Aphodius coenosus, 2024-03-15
1707655, Aphodius coenosus, 2024-03-15
1708036, Aphodius equestris, 2024-03-20
1743112, Aphodius borealis, 2024-05-30

1744017, Aphodius fimetarius, 2024-06-20

The remaining specimen has been assigned NHMD number 001779420, (updated taxon name: Aphodius rufus) and imaged.

The image files (JSON and tif) can be found here: N:\SCI-SNM-DigitalCollections\DaSSCo\MASTER_IMAGE_STORE\Main_image_store\WORKPIOF0001\2024-11-21
timestamped between 13:02 and 13:04 (7 specimens, 14 files total).

The DigiApp export for specimen 001779420 can be found here: N:\SCI-SNM-DigitalCollections\DaSSCo\DigiApp\Data\1.FromDigiApp\NHMD_PinnedInsects
Filename: "NHMD_PinnedInsects_20241121_13_23_JMJ_original.csv"

**Comment by AstridBVW** [comment]
Thank you @JesperMJensen! I will change the status to done on the Mass Digitization App project board and reassign it to myself.

**Comment by AstridBVW** [comment]
Specimen NHMD001779420 has been imported. All the image files have been located and moved to the new folder on the N-drive, N:/SCI-SNM-DigitalCollections/DaSSCo/Uploads_to_Specify_images. The blurry image for NHMD001744017 has been deleted (jpeg, tif and json).
