### ISSUE TITLE
Guided form / Full form

### ISSUE THREAD

**Issue by joaquimsantos1978** [NHMDenmark/DaSSCo-Transcription#24]
The transcription platform has two possible paths for the users:
- guided form (one form with only one field at a time)
- full form (one form with all the fields at once)
The default one is the guided form. There is no memory of preference, so every time the for is loaded it is the displayed option.
Because some fields are related, it is desirable that they are on the same form. For now, displaying the full would solve the problem.

Nevertheless, we should consider other aspects:
- [ ] The possibility to have linked fields, so that they are shown on one form (Coimbra has it working with nested fields, but raises problems for previous submissions when new children fields are added to a form)
- [ ] letting the user chose their preferred path and store it in the user's profile, or as a browser cookie.

**Comment by AstridBVW** [comment]
At our catch up meeting 20241105 we discussed having the full form as the default instead of the guided form for V1. This way all the fields for a specific project will be shown together as a default. We agreed this would be the best solution for now and should be implemented for V1.

Task for @joaquimsantos1978:

- [ ] Change the default form to be the full form

@PipBrewer Since this is something we want for V1, maybe it should have higher priority?

**Comment by AstridBVW** [comment]
Yes, the full form is already an option, but when a user chooses to participate in a project, the guided form will be the default form shown, and they will have to choose the full form instead to have all the fields shown at the same time. And every time they submit their answers, it goes back to the guided form for the next record. So the user will have to choose the full form for every record. This could become quite annoying from a user perspective.

**Comment by PipBrewer** [comment]
@AstridBVW Understood and thank you for the clarification. I didn't realise that it would revert for each record in a session. I agree in that case, that we should up the priority on this.

**Comment by joaquimsantos1978** [comment]
Full form is now the default. We might consider removing the guided form for now, as this might seem confusing for users.

**Comment by PipBrewer** [comment]
> Full form is now the default. We might consider removing the guided form for now, as this might seem confusing for users.

It this is not much work (e.g., just an hour) let's do this

**Comment by joaquimsantos1978** [comment]
very quick. done
