### ISSUE TITLE
Summary of first transcription workshop

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/DaSSCo-Transcription#3]
Summarise the first transcription workshop, capturing (in brief):
- Major takeaways (based on the spreadsheet)
- Things that need to be followed up on/investigated

Send this for review to Pip and Chelsea and then finalise

**Due date: 11/01/2024**

**Comment by PipBrewer** [comment]
Edited and will send around in email for checking by 11/01/2024

[Summary of Transcription Workshop held on 20231107_PBedits.docx](https://github.com/NHMDenmark/DaSSCo-Transcription/files/13792944/Summary.of.Transcription.Workshop.held.on.20231107_PBedits.docx)

**Comment by AstridBVW** [comment]
Summary is finalised and ready to be send out.

[Summary of Transcription Workshop held on 20231107_Final.docx](https://github.com/NHMDenmark/DaSSCo-Transcription/files/13888419/Summary.of.Transcription.Workshop.held.on.20231107_Final.docx)

**Comment by AstridBVW** [comment]
The summary was sent out 20240116.

It has been saved in the following location: 
N:\SCI-SNM-DigitalCollections\DaSSCo\Transcription\Workshop 1 November 2023\Reporting
