### ISSUE TITLE
Collect examples of labels

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/DaSSCo-Transcription#8]
Images of typical labels from collections would be really useful to help inform the decisions on how we will approach capturing specimen data from images (mostly labels and register sheets) as part of mass digitisation.

Contact collection managers/curators for examples. These examples should be typical labels rather than edge cases, so we can see what we will commonly encounter. 

Due date: 02/01/2024

**Comment by AstridBVW** [comment]
After the Christmas break, I will send an email to Christian and Laura explaining what we need. They can pass the request on to the collection managers in their respective sections, and the collection managers can send us images of typical labels from their collections.

**Comment by AstridBVW** [comment]
I have received images of typical labels from most collections (still missing Mammalogy and Herpetology). I have placed the one I have on the N-drive:

N:\SCI-SNM-DigitalCollections\DaSSCo\Transcription\Typical labels

**Comment by AstridBVW** [comment]
I have now also received images from Mammalogy and Herpetology. They are on the N-drive.

Following collections are represented:
- Botany
- Entomology
- Herpetology
- Ichtyology
- Invertebrate Zoology
- Mammalogy
- Ornithology
- Vertebrate Paleontology

We discussed setting up a meeting with curators and collections managers for Geology, I assume we will ask for examples of labels then if we think we need them.

**Comment by AstridBVW** [comment]
Hans Viborg (NHMA) and Birgitte Bergman (AU Herbarium) have now been contacted about images of typical labels and register sheets from their collections.

**Comment by AstridBVW** [comment]
Images of typical labels from NHMA and AU are now available on the N-drive.

N:\SCI-SNM-DigitalCollections\DaSSCo\Transcription\Typical labels
